# [K] (c) 2022

name: UPDATE

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main.yml'
  schedule:
    - cron: '30 20 * * 1'

jobs:
  create:

    runs-on: ubuntu-latest
    if: github.repository == 'kongfl888/openwrt-https-dns-proxy'
    steps:

    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: main

    - name: Set git identity
      run : |
        git config --global user.email "kongfl888@outlook.com"
        git config --global user.name "kongfl888 K"
    - name: Git Init
      run:  |
        . ./patch.sh
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: main
      run:  |
        git push origin $DOWNSTREAM_BRANCH || echo ""
